---
- name: Install ripgrep (macOS)
  package:
    name: rg
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Install ripgrep (Linux)
  package:
    name: ripgrep
    state: present
  when: "{{ is_linux }}"
  become: "{{ linux }}"

- name: Install fd
  package:
    name: fd
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Install libvterm
  become: "{{linux}}"
  package:
    name: libvterm
    state: present
  when: ansible_distribution == 'MacOSX' or ansible_distribution == 'Fedora'

- name: Install libvterm (Ubuntu)
  become: "{{linux}}"
  package:
    name: libvterm-dev
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Emacs (Ubuntu)
  become: "{{linux}}"
  community.general.snap:
    name: emacs
    channel: edge
    classic: yes
  when: ansible_distribution == 'Ubuntu'

- name: Delete current emacs config
  file:
    path: ~/.emacs.d
    state: absent

- name: Delete current DOOM emacs config
  file:
    path: ~/.doom.d
    state: absent

- name: Delete current spacemacs config
  file:
    path: ~/.spacemacs
    state: absent

- name: Install Git
  become: "{{linux}}"
  package:
    name: git
    state: present

- name: Clone DOOM Emacs
  ansible.builtin.git:
    repo: https://github.com/hlissner/doom-emacs
    dest: "{{ansible_env.HOME}}/.emacs.d"

- name: Clone personal DOOM Emacs config
  ansible.builtin.git:
    repo: https://github.com/ruivieira/.doom.d
    dest: "{{ansible_env.HOME}}/.doom.d"

- name: Run DOOM Emacs install
  ansible.builtin.shell:
    cmd: ~/.emacs.d/bin/doom -y install