---
- name: Install sass
  package:
    name: sass/sass/sass
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - devtools

- name: Install PlantUML
  package:
    name: plantuml
    state: present
  become: "{{linux}}"

- name: Install NeoVim
  import_tasks: "{{ role_path }}/tasks/neovim.yaml"
  tags:
    - devtools
    - neovim

- name: Install Spacemacs
  import_tasks: "{{ role_path }}/tasks/spacemacs.yaml"
  tags:
    - devtools
    - spacemacs

- name: Install VSCode
  import_tasks: "{{ role_path }}/tasks/vscode.yaml"
  tags:
    - devtools
    - vscode

- name: Install Python
  import_tasks: "{{ role_path }}/tasks/python.yaml"
  tags:
    - devtools
    - python

- name: Install LISP(s)
  import_tasks: "{{ role_path }}/tasks/lisp.yaml"
  tags:
    - devtools
    - lisp

