---
- name: Install sass
  package:
    name: sass/sass/sass
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - devtools

- name: Install NeoVim
  import_tasks: "{{ role_path }}/tasks/neovim.yaml"
  tags:
    - devtools
    - neovim
