---
- name: Install pyenv (macOS)
  package:
    name: pyenv
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - core
    - devtools
    - python
- name: Configure matplotlib
  block:
    - name: Create matplotlib config dir
      file:
        path: "{{ ansible_env.HOME }}/.matplotlib"
        state: directory
    - name: Copy .matplotlibrc
      copy:
        src: "{{ playbook_dir }}/.matplotlib/matplotlibrc"
        dest: "{{ ansible_env.HOME }}/.matplotlib/matplotlibrc"

- name: Install pyright node.js package globally.
  community.general.npm:
    name: pyright
    global: yes
    state: present
