---
- name: Install ripgrep (macOS)
  package:
    name: rg
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Install libvterm
  package:
    name: libvterm
    state: present
  
- name: Install ripgrep (Linux)
  become: "{{linux}}"
  package:
    name: ripgrep
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install Emacs
  become: "{{linux}}"
  package:
    name: emacs
    state: present

- name: Delete current emacs config
  file:
    path: ~/.emacs.d
    state: absent

- name: Delete current DOOM emacs config
  file:
    path: ~/.doom.d
    state: absent

- name: Delete current spacemacs config
  file:
    path: ~/.spacemacs
    state: absent

- name: Copy spacemacs config
  ansible.builtin.copy:
    src: "{{role_path}}/files/.spacemacs"
    dest: "{{ansible_env.HOME}}/.spacemacs"

- name: Clone spacemacs
  ansible.builtin.git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ansible_env.HOME}}/.emacs.d"

- name: Create banners directory
  file:
    path: ~/.emacs.d/banners
    state: directory

- name: Copy banners
  ansible.builtin.copy:
    src: "{{role_path}}/files/banners/{{item}}"
    dest: "~/.emacs.d/banners/{{item}}"
  with_items:
    - "cat1.png"

- name: Create snippets directory
  file:
    path: ~/.emacs.d/private
    state: directory

- name: Copy snippets
  ansible.builtin.copy:
    src: "{{role_path}}/files/snippets"
    dest: "~/.emacs.d/private/"
