---
- name: Define vscode variables
  set_fact:
    settings_dir_mac: "{{ansible_env.HOME}}/Library/Application\ Support/Code/User/"
    settings_dir_linux: "{{ansible_env.HOME}}/.config/Code/User/"

- name: Install VSCode (Linux)
  block:
    - name: Import RPM keys
      shell: "rpm --import https://packages.microsoft.com/keys/microsoft.asc"
      become: yes
    - name: Create VSCode RPM repo file
      copy:
        dest: "/etc/yum.repos.d/vscode.repo"
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      become: yes
    - name: Install VSCode package
      package:
        name: code
        state: present
      become: yes
  when: ansible_distribution == 'Fedora'

- name: Install VSCode (macOS)
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Install vscode settings (macOS)
  ansible.builtin.copy:
    src: "{{role_path}}/files/settings.json"
    dest: "{{settings_dir_mac}}"
    follow: yes
  when: ansible_distribution == 'MacOSX'

- name: Install vscode settings (Linux)
  ansible.builtin.copy:
    src: "{{role_path}}/files/settings.json"
    dest: "{{settings_dir_linux}}"
    follow: yes
  when: ansible_distribution == 'Fedora'

- name: Install VSCode extensions
  shell: "code --install-extension {{item}}"
  with_items:
    - aeschli.vscode-css-formatter
    - alexcvzz.vscode-sqlite
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - bungcip.better-toml
    - CADENAS.vscode-glsllint
    - christopherstyles.html-entities
    - circledev.glsl-canvas
    - DavidAnson.vscode-markdownlint
    - dawhite.mustache
    - daylerees.rainglow
    - dunstontc.viml
    - eamodio.gitlens
    - glen-anderson.vscode-faust
    - guyskk.language-cython
    - hbenl.vscode-test-explorer
    - iampeterbanjo.elixirlinter
    - jithurjacob.nbpreviewer
    - joaompinto.asciidoctor-vscode
    - justusadam.language-haskell
    - kevinglasson.cornflakes-linter
    - kiegroup.vscode-extension-pack-kogito-kie-editors
    - kosz78.nim
    - kunstmusik.csound-vscode-plugin
    - lightbend.vscode-sbt-scala
    - mactkg.sonic-pi
    - mattn.Lisp
    - mechatroner.rainbow-csv
    - mjmcloug.vscode-elixir
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode-remote.remote-wsl
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-vscode.cpptools
    - octref.vetur
    - pepri.subtitles-editor
    - raczzalan.webgl-glsl-editor
    - redhat.java
    - redhat.vscode-yaml
    - ritwickdey.LiveServer
    - robertrossmann.remedy
    - rust-lang.rust
    - scala-lang.scala
    - scalameta.metals
    - scriplit.perl6-lsp
    - serayuzgur.crates
    - Sir2B.lispbeautifier
    - sjhuangx.vscode-scheme
    - slevesque.shader
    - stayfool.vscode-asciidoc
    - stiansivertsen.visualclojure
    - Swellaby.vscode-rust-test-adapter
    - UCL.haskelly
    - VisualStudioExptTeam.vscodeintellicode
    - vknabel.vscode-swift-development-environment
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vstirbu.vscode-mermaid-preview
    - yzhang.markdown-all-in-one
    - richie5um2.vscode-sort-json
