---
- hosts: localhost
  gather_facts: yes
  tasks:
  - name: Install git
    package:
      name: git
      state: present
  - name: Install asciinema
    package:
      name: asciinema
      state: present
  - name: Install bogbackup
    homebrew_cask:
      name: borgbackup
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install bogbackup
    package:
      name: borgbackup
      state: present
    when: ansible_distribution == 'Fedora'
  - name: Install curl
    package:
      name: curl
      state: present
  - name: Install chicken scheme
    package:
      name: chicken
      state: present
  - name: Install giter8
    package:
      name: giter8
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install go
    package:
      name: go
      state: present
  - name: Install Imagemagick
    package:
      name: imagemagick
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install Imagemagick
    package:
      name: ImageMagick
      state: present
    when: ansible_distribution == 'Fedora'
  - name: Install jEnv (macOS)
    package:
      name: jenv
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install jEnv (Linux)
    command: git clone https://github.com/gcuisinier/jenv.git ~/.jenv
    when: ansible_distribution == 'Fedora'
  - name: Check if MacDown is installed
    stat:
      path: /Applications/MacDown.app
    register: macdown_result
  - name: Install Macdown
    homebrew_cask:
      name: macdown
      state: present
    when:
      - macdown_result.stat.exists == False 
      - ansible_distribution == 'MacOSX'
  - name: Install libsndfile
    package:
      name: libsndfile
      state: present
  - name: Install maven
    package:
      name: maven
      state: present 
  - name: Install pyenv (macOS)
    package:
      name: pyenv
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install pyenv (Linux)
    command: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    when: ansible_distribution == 'Fedora'
  - name: Install scala
    package:
      name: scala
      state: present
  # - name: Install um
  #   package:
  #     name: sinclairtarget/wst/um
  #     state: present
  - name: Install zsh
    package:
      name: zsh
      state: present
  - name: Configure matplotlib
    block:
      - name: Create matplotlib config dir
        file:
          path: "{{ ansible_env.HOME }}/.matplotlib"
          state: directory
      - name: Copy .matplotlibrc
        copy:
          src: "{{ playbook_dir }}/.matplotlib/matplotlibrc"
          dest: "{{ ansible_env.HOME }}/.matplotlib/matplotlibrc"
  - name: Configure um
    block:
      - name: Create um config dir
        file:
          path: "{{ ansible_env.HOME }}/.um"
          state: directory
      - name: Create um config file
        file:
          path: "{{ ansible_env.HOME }}/.um/umconfig"
          state: touch
      - name: Add pages directory to um config file
        lineinfile:
          path: "{{ ansible_env.HOME }}/.um/umconfig"
          line: "pages_directory = {{ ansible_env.HOME }}/code/umpages"
      - name: Add editor to um config file
        lineinfile:
          path: "{{ ansible_env.HOME }}/.um/umconfig"
          line: editor = vim
  - name: Configure zsh
    block:
      - name: Install bash-completion
        package:
          name: bash-completion
          state: present
      - name: Install oh-my-zsh
        git:
          repo: https://github.com/robbyrussell/oh-my-zsh.git
          dest: ~/.oh-my-zsh
      - name: Check if oh-my-zsh auto-completions are installed
        stat:
          path: "{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        register: ohmyzshcompletion_result  
      - name: Install oh-my-zsh auto-completions
        command: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        when: ohmyzshcompletion_result.stat.exists == False 
      - name: Delete current .bash_profile
        file:
          path: "{{ansible_env.HOME}}/.bash_profile"
          state: absent
      - name: Symlink .bashprofile (macOS)
        file:
          src: "{{playbook_dir}}/.bash_profile_mac"
          dest: "{{ansible_env.HOME}}/.bash_profile"
          state: link
        when: ansible_distribution == 'MacOSX'
      - name: Symlink .bashprofile (Linux)
        file:
          src: "{{playbook_dir}}/.bash_profile_linux"
          dest: "{{ansible_env.HOME}}/.bash_profile"
          state: link
        when: ansible_distribution == 'Fedora'
      - name: Delete current .bashrc
        file:
          path: "{{ansible_env.HOME}}/.bashrc"
          state: absent
      - name: Symlink .bashrc
        file:
          src: "{{playbook_dir}}/.bashrc"
          dest: "{{ansible_env.HOME}}/.bashrc"
          state: link
      - name: Symlink .zshrc
        file:
          src: "{{playbook_dir}}/.zshrc"
          dest: "{{ansible_env.HOME}}/.zshrc"
          state: link