---
- hosts: localhost
  gather_facts: yes

  roles:
    - {role: zsh, tags: ['core', 'zsh']}
    - {role: spacemacs, tags: ['editors']}
    - {role: neovim, tags: ['editors']}

  tasks:
  - name: Install git
    package:
      name: git
      state: present
    become: false if ansible_distribution == 'MacOSX' else true
    tags:
      - core
  - name: Install asciinema
    package:
      name: asciinema
      state: present
  - name: Install borgbackup (macOS)
    homebrew_cask:
      name: borgbackup
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install borgbackup (Linux)
    package:
      name: borgbackup
      state: present
    when: ansible_distribution == 'Fedora'
  - name: Install curl
    package:
      name: curl
      state: present
    become: false if ansible_distribution == 'MacOSX' else true
    tags:
      - core
  - name: Install chicken scheme
    package:
      name: chicken
      state: present
  - name: Install giter8
    package:
      name: giter8
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install go
    package:
      name: go
      state: present
  - name: Install Imagemagick
    package:
      name: imagemagick
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install Imagemagick
    package:
      name: ImageMagick
      state: present
    when: ansible_distribution == 'Fedora'
  - name: Install jEnv (macOS)
    package:
      name: jenv
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install jEnv (Linux)
    command: git clone https://github.com/gcuisinier/jenv.git ~/.jenv
    when: ansible_distribution == 'Fedora'
  - name: Check if MacDown is installed
    stat:
      path: /Applications/MacDown.app
    register: macdown_result
  - name: Install Macdown
    homebrew_cask:
      name: macdown
      state: present
    when:
      - macdown_result.stat.exists == False 
      - ansible_distribution == 'MacOSX'
  - name: Install libsndfile
    package:
      name: libsndfile
      state: present
  - name: Install maven
    package:
      name: maven
      state: present 
  - name: Install pyenv (macOS)
    package:
      name: pyenv
      state: present
    when: ansible_distribution == 'MacOSX'
  - name: Install pyenv (Linux)
    command: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    when: ansible_distribution == 'Fedora'
  - name: Install scala
    package:
      name: scala
      state: present
  # - name: Install um
  #   package:
  #     name: sinclairtarget/wst/um
  #     state: present
  - name: Configure matplotlib
    block:
      - name: Create matplotlib config dir
        file:
          path: "{{ ansible_env.HOME }}/.matplotlib"
          state: directory
      - name: Copy .matplotlibrc
        copy:
          src: "{{ playbook_dir }}/.matplotlib/matplotlibrc"
          dest: "{{ ansible_env.HOME }}/.matplotlib/matplotlibrc"
  - name: Configure um
    block:
      - name: Create um config dir
        file:
          path: "{{ ansible_env.HOME }}/.um"
          state: directory
      - name: Create um config file
        file:
          path: "{{ ansible_env.HOME }}/.um/umconfig"
          state: touch
      - name: Add pages directory to um config file
        lineinfile:
          path: "{{ ansible_env.HOME }}/.um/umconfig"
          line: "pages_directory = {{ ansible_env.HOME }}/code/umpages"
      - name: Add editor to um config file
        lineinfile:
          path: "{{ ansible_env.HOME }}/.um/umconfig"
          line: editor = vim
  - name: Create .config directory
    file:
      path: ~/.config
      state: directory
    tags:
        - core
  - name: Install micro editor
    block:
    - name: Install micro editor (macOS)
      package:
        name: micro
        state: present
      when: ansible_distribution == 'MacOSX'
    - name: Install micro editor (Linux)
      shell: curl https://getmic.ro | bash
      args:
        chdir: /usr/bin
      when: ansible_distribution == 'Fedora'
  - name: Install rust
    block:
      - name: Install rustup.sh
        shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
        become: true
    tags:
      - code
      - rust
  - name: Install neofetch (macOS)
    package:
      name: neofetch
      state: present
    become: false if ansible_distribution == 'MacOSX' else true
    tags:
      - core
  - name: Copy images
    shell: "{{item}}"
    with_items:
      - rm -Rf ~/.images
      - mkdir ~/.images
      - cp {{playbook_dir}}/images/* ~/.images
    tags:
      - core
  - name: Copy iTerm2 settings (macOS)
    shell: "{{item}}"
    with_items:
      - mkdir -p ~/.config/iterm2 
      - cp -R {{playbook_dir}}/iterm2/* ~/.config/iterm2
    when: ansible_distribution == 'MacOSX'
    tags:
      - core
  - name: Install gitea
    block:
      - name: Install package (Linux)
        shell: "{{item}}"
        with_items:
          - wget -O gitea https://dl.gitea.io/gitea/1.7.0/gitea-1.7.0-linux-amd64
          - chmod +x gitea
          - cp gitea /usr/local/bin/gitea
        become: true
        when: ansible_distribution == 'Fedora'
      - name: Install package (macOS)
        shell: "{{item}}"
        with_items:
          - wget -O gitea https://dl.gitea.io/gitea/1.7.0/gitea-1.7.0-darwin-10.6-amd64
          - chmod +x gitea
          - cp gitea /usr/local/bin/gitea
        become: true
        when: ansible_distribution == 'MacOSX'
    tags:
      - gitea
  - name: Install iJava (Jupyter kernel)
    become: 
    shell: "{{item}}"
    with_items:
      - wget -O /tmp/ijava-1.2.0.zip https://github.com/SpencerPark/IJava/releases/download/v1.2.0/ijava-1.2.0.zip
      - unzip /tmp/ijava-1.2.0.zip -d /tmp/ijava-1.2.0
      - python3 /tmp/ijava-1.2.0/install.py --sys-prefix
    become: false if ansible_distribution == 'MacOSX' else true
    tags:
      - jupyter
  - name: Install byobu
    package:
      name: byobu
      state: present
    become: false if ansible_distribution == 'MacOSX' else true
    tags:
      - core
  - name: Install beets
    pip:
      name: beets
    tags:
      - sound

        