DOTFILES_ROOT := $(shell pwd)

all: emacs spacemacs pyenv maven scala sbt profile

sbt:
	@echo "Installing sbt"
	@curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
	sudo yum install -y sbt

scala:
	@echo "Install scala"
	@wget http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.rpm
	@sudo yum install -y scala-2.11.8.rpm
	@rm scala-2.11.8.rpm