---
- hosts: localhost
  gather_facts: yes
  vars:
    linux: "{{ 'no' if ansible_distribution == 'MacOSX' else 'yes'}}"
    is_linux: "{{ linux == 'yes' }}"

  roles:
    - { role: core, tags: [core] }
    - { role: backup, tags: [backup] }
    - { role: cli, tags: [cli] }
    - { role: language, tags: [language] }
    - { role: devtools, tags: [devtools] }
    - { role: zsh, tags: [zsh] }

    - { role: jdk, tags: [jdk, code] }
    - { role: config, tags: [config] }
    - { role: fonts, tags: [fonts] }
    - { role: rust, tags: [rust] }
    - { role: ui, tags: [ui, xfce] }
    - { role: comms, tags: [comms, irc]}

  # Core dependencies
