---
- hosts: all
  gather_facts: yes
  vars:
    linux: "{{ 'no' if ansible_distribution == 'MacOSX' else 'yes'}}"

  roles:
    - { role: core, tags: [core] }
    - { role: backup, tags: [backup] }
    - { role: cli, tags: [cli] }
    - { role: devtools, tags: [devtools] }
    - { role: zsh, tags: [zsh] }

    - { role: jdk, tags: [jdk, code] }
    - { role: config, tags: [config] }
    - { role: fonts, tags: [fonts] }
    - { role: rust, tags: [rust] }

  # Core dependencies