---
- name: Define vscode variables
  set_fact:
    settings_dir_mac: ~/Library/Application\ Support/Code/User/
    settings_dir_linux: ~/.config/Code/User/
- name: Install VSCode (Linux)
  block:
    - name: Import RPM keys
      shell: "rpm --import https://packages.microsoft.com/keys/microsoft.asc"
      become: yes
    - name: Create VSCode RPM repo file
      copy:
        dest: "/etc/yum.repos.d/vscode.repo"
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      become: yes
    - name: Install VSCode package
      package:
        name: code
        state: present
      become: yes
  when: ansible_distribution == 'Fedora'
  tags:
    - code
    - editors
- name: Install vscode settings (macOS)
  shell: "{{item}}"
  with_items:
    - mkdir -p {{settings_dir_mac}}
    - cp  {{role_path}}/files/settings.json {{settings_dir_mac}}
  when: ansible_distribution == 'MacOSX'
- name: Install vscode settings (Linux)
  shell: "{{item}}"
  with_items:
    - mkdir -p {{settings_dir_linux}}
    - cp  {{role_path}}/files/settings.json {{settings_dir_linux}}
  when: ansible_distribution == 'Fedora'
- name: Install VSCode extensions
  shell: "code --install-extension {{item}}"
  with_items:
    - 0x9ef.vscode-vlang
    - aeschli.vscode-css-formatter
    - bungcip.better-toml
    - DavidAnson.vscode-markdownlint
    - dawhite.mustache
    - daylerees.rainglow
    - dunstontc.viml
    - eamodio.gitlens
    - faustinoaq.crystal-lang
    - glen-anderson.vscode-faust
    - hbenl.vscode-test-explorer
    - iampeterbanjo.elixirlinter
    - jithurjacob.nbpreviewer
    - justusadam.language-haskell
    - kosz78.nim
    - kunstmusik.csound-vscode-plugin
    - lightbend.vscode-sbt-scala
    - mactkg.sonic-pi
    - mattn.Lisp
    - mjmcloug.vscode-elixir
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode.cpptools
    - ms-vscode.Go
    - npruehs.pony
    - pepri.subtitles-editor
    - redhat.java
    - ritwickdey.LiveServer
    - rust-lang.rust
    - scala-lang.scala
    - scalameta.metals
    - scriplit.perl6-lsp
    - serayuzgur.crates
    - Sir2B.lispbeautifier
    - sjhuangx.vscode-scheme
    - stayfool.vscode-asciidoc
    - stiansivertsen.visualclojure
    - Swellaby.vscode-rust-test-adapter
    - tiehuis.zig
    - UCL.haskelly
    - VisualStudioExptTeam.vscodeintellicode
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - yzhang.markdown-all-in-one