---
- name: Install git
  package:
    name: git
    state: present
  become: "{{ linux }}"
  tags:
    - core

- name: Install curl
  package:
    name: curl
    state: present
  become: "{{ linux }}"
  tags:
    - core
- name: Create .config directory
  file:
    path: ~/.config
    state: directory
  tags:
    - core
- name: Install neofetch
  package:
    name: neofetch
    state: present
  become: "{{ linux }}"
  tags:
    - core
- name: Install chezmoi (macOS)
  package:
    name: chezmoi
    state: present
  tags:
    - core
  when: ansible_distribution == 'MacOSX'

- name: Install chezmoi (Linux)
  community.general.snap:
    name: chezmoi
    classic: yes
  become: "{{ linux }}"
  tags:
    - core
  when: "{{ is_linux }}"

- name: Install keepassxc
  package:
    name: keepassxc
    state: present
  become: "{{ linux }}"
  tags:
    - core

- name: Install sqlite3
  package:
    name: sqlite3
    state: present
  become: "{{ linux }}"
  tags:
    - core
