---
- name: Install git
  package:
    name: git
    state: present
  become: "{{ linux }}"
  tags:
    - core
- name: Install curl
  package:
    name: curl
    state: present
  become: "{{ linux }}"
  tags:
    - core
- name: Create .config directory
  file:
    path: ~/.config
    state: directory
  tags:
    - core
- name: Install neofetch
  package:
    name: neofetch
    state: present
  become: "{{ linux }}"
  tags:
    - core
- name: Install chezmoi (macOS)
  package:
    name: chezmoi
    state: present
  tags:
    - core
  when: ansible_distribution == 'MacOSX'
- name: Install chezmoi (Fedora)
  dnf:
    name: 'https://github.com/twpayne/chezmoi/releases/download/v2.0.15/chezmoi-2.0.15-x86_64.rpm'
    state: present
    disable_gpg_check: yes
  become: "{{ linux }}"
  tags:
    - core
  when: ansible_distribution == 'Fedora'
- name: Install keepassxc (macOS)
  homebrew_cask:
    name: keepassxc
    state: present
  when: ansible_distribution == 'MacOSX'

