- name: Install Alacritty
  community.general.snap:
    name: alacritty
    classic: yes
  become: "{{linux}}"
  when: ansible_distribution == 'Ubuntu'

- name: Create Alacritty config dir
  file:
    path: ~/.config/alacritty
    state: directory

- name: Copy Alacritty config
  ansible.builtin.copy:
    src: "{{role_path}}/files/{{item}}"
    dest: "~/.config/alacritty/{{item}}"
  with_items:
    - "alacritty.yml"
