- name: Create images dir
  file:
    path: ~/.local/share/images
    state: directory

- name: Copy images
  ansible.builtin.copy:
    src: "{{role_path}}/files/images/{{item}}"
    dest: "~/.images/{{item}}"
  with_items:
    - "up.png"
    - "mars-sunset.jpg"
