---
- name: Setup i3
  import_tasks: "{{ role_path }}/tasks/i3.yaml"
  tags:
    - ui
    - ubuntu

- name: Install images
  import_tasks: "{{ role_path }}/tasks/images.yaml"
  tags:
    - ui
    - images
    
- name: Setup Alacritty
  import_tasks: "{{ role_path }}/tasks/alacritty.yaml"
  tags:
    - ui

- name: Setup Wezterm
  import_tasks: "{{ role_path }}/tasks/wezterm.yaml"
  tags:
    - ui
    - wezterm

- name: Setup Ubuntu UI
  import_tasks: "{{ role_path }}/tasks/ubuntu.yaml"
  tags:
    - ui
    - ubuntu  
  when: ansible_distribution == 'Ubuntu'

- name: Setup Xfce UI
  import_tasks: "{{ role_path }}/tasks/xfce.yaml"
  tags:
    - ui
    - xfce
  when: ansible_distribution == 'Ubuntu'

- name: Setup Joplin
  import_tasks: "{{ role_path }}/tasks/joplin.yaml"
  tags:
    - ui
    - joplin

- name: Setup AwesomeWM UI
  import_tasks: "{{ role_path }}/tasks/awesomewm.yaml"
  tags:
    - ui
    - awesomewm
  when: "{{ is_linux }}"

- name: Setup Kitty
  import_tasks: "{{ role_path }}/tasks/kitty.yaml"
  tags:
    - ui
    - kitty

- name: Setup Xmodmap to be macOS-like
  ansible.builtin.copy:
    src: "{{role_path}}/files/.Xmodmap"
    dest: "~/.Xmodmap"
  when: "{{ is_linux }}"

- name: Setup Sublime Text
  import_tasks: "{{ role_path }}/tasks/sublime.yaml"
  tags:
    - ui
    - sublime