- name: define Sublime Text variables
  set_fact:
    sublime_config_dir: "~/Library/Application\ Support/Sublime\ Text/Packages"

- name: Copy Sublime Text user configuration
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sublime/Packages/User/"
    dest: "{{ sublime_config_dir }}/User/"