---
- name: Install pyenv (macOS)
  package:
    name: pyenv
    state: present
  when: ansible_distribution == 'MacOSX'
- name: Install pyenv (Linux)
  command: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  when: ansible_distribution == 'Fedora'
- name: Configure matplotlib
  block:
    - name: Create matplotlib config dir
      file:
        path: "{{ ansible_env.HOME }}/.matplotlib"
        state: directory
    - name: Copy .matplotlibrc
      copy:
        src: "{{ playbook_dir }}/.matplotlib/matplotlibrc"
        dest: "{{ ansible_env.HOME }}/.matplotlib/matplotlibrc"
- name: Install numpy
  pip:
    name: numpy
- name: Install matplotlib
  pip:
    name: matplotlib
- name: Install scipy
  pip:
    name: scipy
