---
- name: define Python variables
  set_fact:
    ijava_dest: /tmp/ijava-1.2.0
    java_version: jdk-11.0.2.jdk


- name: Install pyenv (macOS)
  package:
    name: pyenv
    state: present
  when: ansible_distribution == 'MacOSX'
- name: Install pyenv (Linux)
  command: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  when: ansible_distribution == 'Fedora'
- name: Configure matplotlib
  block:
    - name: Create matplotlib config dir
      file:
        path: "{{ ansible_env.HOME }}/.matplotlib"
        state: directory
    - name: Copy .matplotlibrc
      copy:
        src: "{{ playbook_dir }}/.matplotlib/matplotlibrc"
        dest: "{{ ansible_env.HOME }}/.matplotlib/matplotlibrc"
- name: Install Jupyter
  pip:
    name: jupyter
  tags:
    - jupyter
- name: Install numpy
  pip:
    name: numpy
- name: Install matplotlib
  pip:
    name: matplotlib
- name: Install scipy
  pip:
    name: scipy
- name: Install iJava (Jupyter kernel)
  shell: "{{item}}"
  with_items:
    - wget -O {{ijava_dest}}.zip https://github.com/SpencerPark/IJava/releases/download/v1.2.0/ijava-1.2.0.zip
    - unzip -o {{ijava_dest}}.zip -d {{ijava_dest}}
  become: true
  tags:
    - jupyter
- name: Run iJava script
  shell: 
    cmd: "python3 {{ijava_dest}}/install.py --sys-prefix"
    chdir: "{{ijava_dest}}"
  environment:
      JAVA_HOME: /Library/Java/JavaVirtualMachines/{{java_version}}
  tags:
  - jupyter

