---
- name: Install pyenv (macOS)
  package:
    name: pyenv
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - core
    - python
- name: Install pyenv (Linux)
  command: curl https://pyenv.run | sh
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'Alpine' 
  become: yes
  tags:
    - core
    - python
- name: Configure matplotlib
  block:
    - name: Create matplotlib config dir
      file:
        path: "{{ ansible_env.HOME }}/.matplotlib"
        state: directory
    - name: Copy .matplotlibrc
      copy:
        src: "{{ playbook_dir }}/.matplotlib/matplotlibrc"
        dest: "{{ ansible_env.HOME }}/.matplotlib/matplotlibrc"