- name: Import Kopia GPG RPM key
  ansible.builtin.rpm_key:
    state: present
    key: https://kopia.io/signing-key
  when: "{{ is_linux }}"
 
- name: Add Kopia Yum repository
  copy:
    dest: "/etc/yum.repos.d/kopia.repo"
    content: |
      [Kopia]
      name=Kopia
      baseurl=http://packages.kopia.io/rpm/stable/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://kopia.io/signing-key
  when: "{{ is_linux }}"

- name: Install Kopia
  become: "{{ is_linux }}"
  ansible.builtin.package:
    name: kopia
    state: present

- name: Copy Kopia ignore settings
  ansible.builtin.copy:
    src: "{{role_path}}/files/.kopiaignore"
    dest: "~/Sync/code/.kopiaignore"