- name: enable Fedora COPR for restic
  become: yes
  command: "dnf copr enable -y copart/restic"
  when: ansible_distribution == 'Fedora'
  tags:
    - backup
- name: Install restic
  package:
    name: restic
    state: present
  become: "{{ linux }}"
  tags:
    - backup
- name: Install Kopia
  package:
    name: kopia
    state: present
  become: "{{ linux }}"
  tags:
    - backup  
