- name: Install Kopia for Fedora
  import_tasks: "{{ role_path }}/tasks/kopia-fedora.yaml"
  when: ansible_distribution == 'Fedora'
  tags:
    - backup

- name: Install Syncthing
  package:
    name: syncthing
    state: present
  become: "{{ linux }}"
  tags:
    - backup  
