- name: Install Kopia
  become: "{{linux}}"
  import_tasks: "{{ role_path }}/tasks/kopia.yaml"
  tags:
    - backup
    - kopia

- name: Install Syncthing
  package:
    name: syncthing
    state: present
  become: "{{ linux }}"
  tags:
    - backup  
