---
- name: Copy .stignore
  copy:
    src: "{{ role_path }}/files/.stignore"
    dest: ~/Sync/.stignore
  tags:
    - backup
- name: enable Fedora COPR for restic
  command: "dnf copr enable -y copart/restic"
  become: yes
  when: ansible_distribution == 'Fedora'
- name: Install restic
  package:
    name: restic
    state: present
  become: "{{linux}}"
