---
- name: import Crystal RPM GPG key
  shell: rpm --import https://dist.crystal-lang.org/rpm/RPM-GPG-KEY
  become: yes
  when: ansible_distribution == 'Fedora'
- name: create Crystal repo
  copy:
    dest: /etc/yum.repos.d/crystal.repo
    content: |
      [crystal]
      name = Crystal
      baseurl = https://dist.crystal-lang.org/rpm/
  when: ansible_distribution == 'Fedora'
  become: yes
- name: install Crystal
  package:
    name: crystal
    state: present
  become: "{{linux}}"
- name: clone Scry
  git:
    repo: "https://github.com/crystal-lang-tools/scry.git"
    dest: "/tmp/scry"
  become: yes
- name: build Scry
  command: shards build -v
  args:
    chdir: /tmp/scry
  become: yes
- name: copy Scry binary
  copy:
    src: /tmp/scry/bin/scry
    dest: /usr/local/bin/
    mode: a+x
  become: yes