---
- name: Instal libvirtd (Linux)
  package:
    name: libvirtd
    states: present
  when: ansible_distribution == 'Fedora'
  tags:
    - core
- name: Enable libvirtd (Linux)
  systemd:
    name: libvirtd
    enabled: yes
    masked: no
    state: started
  when: ansible_distribution == 'Fedora'
  tags:
    - config
- name: Instal tinyproxy (Linux)
  package:
    name: tinyproxy
    states: present
  when: ansible_distribution == 'Fedora'
  tags:
    - core  
- name: Enable tinyproxy (Linux)
  systemd:
    name: tinyproxy
    enabled: yes
    masked: no
    state: started
  when: ansible_distribution == 'Fedora'
  tags:
    - config
