---
- name: Copy wallpapers (Linux)
  shell: "{{item}}"
  with_items:
    - mkdir -p ~/.wallpapers
    - cp {{role_path}}/files/vw.png ~/.wallpapers
  when: ansible_distribution == 'Fedora'
- name: Set wallpapers (Linux)
  shell: "{{item}}"
  with_items:
    - gsettings set org.gnome.desktop.background picture-uri file:///$HOME/.wallpapers/vw.png
  when: ansible_distribution == 'Fedora'
