---
- name: Create wallpapers directory (Linux)
  ansible.builtin.file:
    path: ~/.wallpapers
    state: directory
    mode: '0755'
  when: ansible_distribution == 'Fedora'

- name: Copy main wallpaper (Linux)
  ansible.builtin.copy:
    src: "{{role_path}}/files/vw.png"
    dest: "~/.wallpapers/vw.png"
    follow: yes
  when: ansible_distribution == 'Fedora'

- name: Set wallpapers (Linux)
  shell: "{{item}}"
  with_items:
    - gsettings set org.gnome.desktop.background picture-uri file:///$HOME/.wallpapers/vw.png
  when: ansible_distribution == 'Fedora'
- name: Create fonts dir (Linux)
  shell: mkdir -p ~/.fonts
- name: Copy fonts (Linux)
  shell: cp {{playbook_dir}}/fonts/{{item}} ~/.fonts
  with_items:
    - firacode/FiraCode-Bold.ttf
    - firacode/FiraCode-Light.ttf
    - firacode/FiraCode-Medium.ttf
    - firacode/FiraCode-Regular.ttf
    - firacode/FiraCode-Retina.ttf
    - jetbrains/JetBrainsMono-Bold-Italic.ttf
    - jetbrains/JetBrainsMono-Bold.ttf
    - jetbrains/JetBrainsMono-ExtraBold-Italic.ttf
    - jetbrains/JetBrainsMono-ExtraBold.ttf
    - jetbrains/JetBrainsMono-Italic.ttf
    - jetbrains/JetBrainsMono-Medium-Italic.ttf
    - jetbrains/JetBrainsMono-Medium.ttf
    - jetbrains/JetBrainsMono-Regular.ttf
  when: ansible_distribution == 'Fedora'
- name: Rebuild font cache (Linux)
  shell: fc-cache
  when: ansible_distribution == 'Fedora'
- name: Enable sshd (Linux)
  systemd:
      name: sshd
      enabled: yes
      masked: no
      state: started
  when: ansible_distribution == 'Fedora'
  tags:
      - config
- name: Install fzf (macOS)
  package:
    name: fzf
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - core
- name: Remove pet (macOS)
  package:
    name: knqyf263/pet/pet
    state: absent
  when: ansible_distribution == 'MacOSX'
  tags:
    - core    
- name: Remove pet (Linux)
  package: 
    name: https://github.com/knqyf263/pet/releases/download/v0.3.0/pet_0.3.0_linux_amd64.rpm
    state: absent
  when: ansible_distribution == 'Fedora'
  tags:
    - core

### Install navi snippet completion

- name: Install navi (macOS)
  package:
    name: denisidoro/tools/navi
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - navi