---
- name: Copy wallpapers (Linux)
  shell: "{{item}}"
  with_items:
    - mkdir -p ~/.wallpapers
    - cp {{role_path}}/files/vw.png ~/.wallpapers
  when: ansible_distribution == 'Fedora'
- name: Set wallpapers (Linux)
  shell: "{{item}}"
  with_items:
    - gsettings set org.gnome.desktop.background picture-uri file:///$HOME/.wallpapers/vw.png
  when: ansible_distribution == 'Fedora'
- name: Create fonts dir (Linux)
  shell: mkdir -p ~/.fonts
- name: Copy fonts (Linux)
  shell: cp {{playbook_dir}}/fonts/{{item}} ~/.fonts
  with_items:
    - firacode/FiraCode-Bold.ttf
    - firacode/FiraCode-Light.ttf
    - firacode/FiraCode-Medium.ttf
    - firacode/FiraCode-Regular.ttf
    - firacode/FiraCode-Retina.ttf
  when: ansible_distribution == 'Fedora'
- name: Rebuild font cache (Linux)
  shell: fc-cache
- name: Enable sshd (Linux)
  systemd:
      name: sshd
      enabled: yes
      masked: no
      state: started
  when: ansible_distribution == 'Fedora'
  tags:
      - config
- name: Install fzf (macOS)
  package:
    name: fzf
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - core
- name: Install pet (macOS)
  package:
    name: knqyf263/pet/pet
    state: present
  when: ansible_distribution == 'MacOSX'
  tags:
    - core    
- name: Install pet (Linux)
  package: 
    name: https://github.com/knqyf263/pet/releases/download/v0.3.0/pet_0.3.0_linux_amd64.rpm
    state: present
  when: ansible_distribution == 'Fedora'
  tags:
    - core
  