---
- name: Install Julia Mono font (macOS)
  copy:
    src: "{{ item }}"
    dest: "~/Library/Fonts/"
  with_fileglob:
    - "{{ role_path }}/files/juliamono/*.ttf"
  when: ansible_distribution == 'MacOSX'
  tags:
    - fonts

- name: Install Julia Mono font (Linux)
  copy:
    src: "{{ item }}"
    dest: "~/.local/share/fonts/"
  with_fileglob:
    - "{{ role_path }}/files/juliamono/*.ttf"
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'Ubuntu'
  tags:
    - fonts

- name: Refresh font cache
  shell: fc-cache -fv
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'Ubuntu'
